config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :images
  resources :users
  root to: "images#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
    has_one_attached :photo
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  # GET /images
  # GET /images.json
  def index
    
    @images = Image.all.where(public: "true")
    
  end


  # GET /images/new
  def new
    @current_user = User.find_by_id(current_user.id)
    @image = @current_user.images.new
  end


  # POST /images
  # POST /images.json
  def create
    @current_user = User.find_by_id(current_user.id)
    @image_array = params[:image][:photo]
    # loops through array of images submitted and create and image model for each of them
    for image in @image_array do
      if (@image_array.index(image) == @image_array.length - 1) 
        @image = @current_user.images.new(public: image_params[:public])
        @image.photo.attach(image)
        respond_to do |format|
          if @image.save
            format.html { redirect_to images_url, notice: 'Images were successfully uploaded.' }
            format.json { render :show, status: :created, location: @images }
          else
            format.html { render :new }
            format.json { render json: @image.errors, status: :unprocessable_entity }
          end
        end
      else
          @image = @current_user.images.new(public: image_params[:public])
          @image.photo.attach(image)
          @image.save
      end
    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:public, :photo)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find_by_id(params[:id])
        if (@user && current_user)
            if (current_user.id == params[:id].to_i)
                @images = @user.images.all
            end 
        else
            @images = @user.images.all.where(public: 'true')
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_form.html.erb
<%= form_with(model: image, local: true) do |form| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
        <% image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, multiple: true %>
  </div>

  <div class="permissions">
    <%= form.label :public, "Public" %>
    <%= form.radio_button :public, "true", required: true %>
    <%= form.label :private, "Private" %>
    <%= form.radio_button :public, "false", required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>
<div id='images-page'>
  <div id='new-image'>
    <%= link_to 'New Image', new_image_path %>
  </div>
  <div id='image-column'>
    <h1>Public Images:</h1>
    <% @images.each do |image| %>
      <%= image_tag( image.photo, width: 400) if image.photo.attached? %>
    <% end %>
    <br>
  </div>
  <div id='users-column'>
    <h2>Users:</h2>
    <% User.all.each do |user| %>
      <%= link_to user.email, user %>
    <% end %>
  </div>
</div>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageRepo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if (user_signed_in?) %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path%>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb

<div id='user-page'>
  <div id='col1'>
  </div>
  <div id='image-column'>
    <% if (@user) %>
      <%= @user.email %>
      <% @images.each do |image| %>
        <tr>
          <%= image_tag( image.photo, height: 300) if image.photo.attached? %>
        </tr>
      <% end %>
    <% else %>
      User not found
    <% end %>
  </div>
  <div id='users-column'>
    <h2>Users:</h2>
    <% User.all.each do |user| %>
      <%= link_to user.email, user %>
    <% end %>
  </div>
</div>